import Notify from "@/Components/notify";
import "./globals.css";
import type { Metadata } from "next";
import NavScrollExample from "@/Components/Appbar";
import Footer from "@/Components/Footer";
import { Course_Context } from "@/context/course_context";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata: Metadata = {
  title: "Littleninjas 🚀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Course_Context>
        <body>
          <Notify />
          <NavScrollExample />
          {children}
          <Footer />
          <ToastContainer
            position="bottom-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss={false}
            draggable
         
            theme="dark"
          />
        </body>
      </Course_Context>
    </html>
  );
}
