import Notify from '@/Components/notify'
import './globals.css'
import type { Metadata } from 'next'
import NavScrollExample from '@/Components/Appbar'
import Footer from '@/Components/Footer'
import { Course_Context } from '@/context/course_context'
export const metadata: Metadata = {
        title: 'Littleninjas 🚀',
        description: 'Generated by create next app',
};

export default function RootLayout({
        children,
}: {
        children: React.ReactNode
}) {

        return (
                <html lang="en">
                        <Course_Context>
                                <body >
                                        <Notify />
                                        <NavScrollExample />
                                        {children}
                                        <Footer />
                                </body>
                        </Course_Context>
                </html>
        )
}
