import Notify from '@/Components/notify'
import './globals.css'
import type { Metadata } from 'next'
import NavScrollExample from '@/Components/Appbar'




export const metadata: Metadata = {
  title: 'Littleninjas 🚀',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Notify/>
        <NavScrollExample/>
        {children}
        </body>
    </html>
  )
}
